export const tiposIdentificacion = [
    { value: 0, label: 'CÉDULA' },
    { value: 1, label: 'RUC' },
    { value: 2, label: 'PASAPORTE' }
]

export const tiposIdentificacionSRI = [
    { value: "05", label: 'CÉDULA' },
    { value: "04", label: 'RUC' },
    { value: "06", label: 'PASAPORTE' },
    { value: "07", label: "VENTA A CONSUMIDOR FINAL" },
    { value: "08", label: "IDENTIFICACIÓN DEL EXTERIOR" },
    { value: "09", label: "PLACA" }
]

export const tiposDocumentos = [
    { value: 1, label: 'FACTURA' },
    { value: 2, label: 'NOTA DE CRÉDITO' },
    { value: 3, label: 'NOTA DE DÉBITO' },
    { value: 4, label: 'GUÍA DE REMISIÓN' },
    { value: 5, label: 'COMPROBANTE DE RETENCIÓN' },
    { value: 6, label: 'LIQUIDACIÓN DE COMPRA' },
]

export const estadosSRI = [
    { value: 0, label: 'GENERADO' },
    { value: 1, label: 'DEVUELTO' },
    { value: 2, label: 'RECIBIDO' },
    { value: 3, label: 'NO AUTORIZADO' },
    { value: 4, label: 'AUTORIZADO' },
    { value: 5, label: 'ANULADO' },
]

export const estadoCorreos = [
    { value: 0, label: 'NO ENVIADO' },
    { value: 1, label: 'ENVIADO' },
    { value: 2, label: 'REBOTADO' },
    { value: 3, label: 'LEÍDO' },
    { value: 4, label: 'NO APLICA' }
]

export const ambientesSRI = [
    { value: 2, label: "PRODUCCIÓN" },
    { value: 1, label: "PRUEBA" }
]

export const formasPago = [
    { value: "01", label: "SIN UTILIZACIÓN DEL SISTEMA FINANCIERO" },
    { value: "15", label: "COMPENSACIÓN DE DEUDAS" },
    { value: "16", label: "TARJETA DE DÉBITO" },
    { value: "17", label: "DINERO ELECTRÓNICO" },
    { value: "18", label: "TARJETA PREPAGO" },
    { value: "19", label: "TARJETA DE CRÉDITO" },
    { value: "20", label: "OTROS CON UTILIZACIÓN DEL SISTEMA FINANCIERO" },
    { value: "21", label: "ENDOSO DE TÍTULOS" }
]

export const tarifasIvas = [
    { value: 0, label: "0%" },
    { value: 2, label: "12%" },
    { value: 6, label: "No Objeto de Impuesto" },
    { value: 7, label: "Exento de IVA" }
]

export const documentosRetenibles = [
    { value: "01", label: "FACTURA" },
    { value: "02", label: "NOTA DE VENTA" },
    { value: "03", label: "LIQ. DE COMPRA" },
    { value: "20", label: "DOC. EMITIDO ESTADO" },
];

export const tiposImpuestos = [
    // IVA
    { value: "2", label: "IVA" },
    { value: "3", label: "ICE" },
    // {value: "5", label: "IRBPNR"}
]

export const impuestosRetencion = [
    { value: 1, label: "RENTA" },
    { value: 2, label: "IVA" },
    { value: 6, label: "ISD" },
]

export const porcentajesRetencion = (impuesto) => {
    if (impuesto === 2) {
        return [
            { value: "7", label: "0%", valor: 0 },
            { value: "9", label: "10%", valor: 10 },
            { value: "10", label: "20%", valor: 20 },
            { value: "1", label: "30%", valor: 30 },
            { value: "11", label: "50%", valor: 50 },
            { value: "2", label: "70%", valor: 70 },
            { value: "3", label: "100%", valor: 100 },
            { value: "8", label: "NO PROCEDE", valor: 0 },
        ]
    } else if (impuesto === 6) {
        return [
            { value: "4580", label: "5%", valor: 5 }
        ]
    } else {
        return [
            { value: "303", label: "303 (10%)", valor: 10 },
            { value: "304", label: "304 (8%)", valor: 8 },
            { value: "304A", label: "304A (8%)", valor: 8 },
            { value: "304B", label: "304B (8%)", valor: 8 },
            { value: "304C", label: "304C (8%)", valor: 8 },
            { value: "304D", label: "304D (8%)", valor: 8 },
            { value: "304E", label: "304E (8%)", valor: 8 },
            { value: "307", label: "307 (2%)", valor: 2 },
            { value: "308", label: "308 (10%)", valor: 10 },
            { value: "309", label: "309 (1.75%)", valor: 1.75 },
            { value: "310", label: "310 (1%)", valor: 1 },
            { value: "311", label: "311 (2%)", valor: 2 },
            { value: "312", label: "312 (1.75%)", valor: 1.75 },
            { value: "312A", label: "312A (1%)", valor: 1 },
            { value: "312B", label: "312B (1%)", valor: 1 },
            { value: "314A", label: "314A (8%)", valor: 8 },
            { value: "314B", label: "314B (8%)", valor: 8 },
            { value: "314C", label: "314C (8%)", valor: 8 },
            { value: "314D", label: "314D (8%)", valor: 8 },
            { value: "319", label: "319 (1.75%)", valor: 1.75 },
            { value: "320", label: "320 (8%)", valor: 8 },
            { value: "322", label: "322 (1.75%)", valor: 1.75 },
            { value: "323", label: "323 (2%)", valor: 2 },
            { value: "323A", label: "323A (2%)", valor: 2 },
            { value: "323B1", label: "323B1 (2%)", valor: 2 },
            { value: "323E", label: "323E (2%)", valor: 2 },
            { value: "323E2", label: "323E2 (0%)", valor: 0 },
            { value: "323F", label: "323F (2%)", valor: 2 },
            { value: "323G", label: "323G (2%)", valor: 2 },
            { value: "323H", label: "323H (2%)", valor: 2 },
            { value: "323I", label: "323I (2%)", valor: 2 },
            { value: "323M", label: "323M (2%)", valor: 2 },
            { value: "323N", label: "323N (0%)", valor: 0 },
            { value: "323O", label: "323O (0%)", valor: 0 },
            { value: "323P", label: "323P (2%)", valor: 2 },
            { value: "323Q", label: "323Q (2%)", valor: 2 },
            { value: "323R", label: "323R (0%)", valor: 0 },
            { value: "323S", label: "323S (2%)", valor: 2 },
            { value: "323T", label: "323T (0%)", valor: 0 },
            { value: "323U", label: "323U (0%)", valor: 0 },
            { value: "324A", label: "324A (1%)", valor: 1 },
            { value: "324B", label: "324B (1%)", valor: 1 },
            { value: "324C", label: "324C (1%)", valor: 1 },
            { value: "325", label: "325 (22%)", valor: 22 },
            { value: "325A", label: "325A (22%)", valor: 22 },
            { value: "326", label: "326 (0%)", valor: 0 },
            { value: "327", label: "327 (0%)", valor: 0 },
            { value: "328", label: "328 (0%)", valor: 0 },
            { value: "329", label: "329 (0%)", valor: 0 },
            { value: "331", label: "331 (0%)", valor: 0 },
            { value: "332", label: "332 (0%)", valor: 0 },
            { value: "332B", label: "332B (0%)", valor: 0 },
            { value: "332C", label: "332C (0%)", valor: 0 },
            { value: "332D", label: "332D (0%)", valor: 0 },
            { value: "332E", label: "332E (0%)", valor: 0 },
            { value: "332F", label: "332F (0%)", valor: 0 },
            { value: "332G", label: "332G-N/A", valor: 0 },
            { value: "332H", label: "332H (0%)", valor: 0 },
            { value: "332I", label: "332I (0%)", valor: 0 },
            { value: "333", label: "333 (10%)", valor: 10 },
            { value: "334", label: "334 (1%)", valor: 1 },
            { value: "335", label: "335 (15%)", valor: 15 },
            { value: "336", label: "336 (0.002%)", valor: 0.002 },
            { value: "337", label: "337 (0.003%)", valor: 0.003 },
            { value: "338", label: "338 (1%)", valor: 1 },
            { value: "340", label: "340 (3%)", valor: 3 },
            { value: "343", label: "343 (1%)", valor: 1 },
            { value: "343A", label: "343A (1%)", valor: 1 },
            { value: "343B", label: "343B (1.75%)", valor: 1.75 },
            { value: "343C", label: "343C (1%)", valor: 1 },
            { value: "3440", label: "3440 (2.75%)", valor: 2.75 },
            { value: "344A", label: "344A (2%)", valor: 2 },
            { value: "344B", label: "344B (2%)", valor: 2 },
            { value: "345", label: "345 (8%)", valor: 8 },
            { value: "346", label: "346 (0%)", valor: 0 },
            { value: "346A", label: "346A (0%)", valor: 0 },
            { value: "346B", label: "346B (0%)", valor: 0 },
            { value: "346C", label: "346C (0%)", valor: 0 },
            { value: "346D", label: "346D (0%)", valor: 0 },
            { value: "348", label: "348 (1%)", valor: 1 },
            { value: "350", label: "350 (1.50%)", valor: 1.50 },
            { value: "500", label: "500 (25%)", valor: 25 },
            { value: "501", label: "501 (25%)", valor: 25 },
            { value: "501A", label: "501A (25%)", valor: 25 },
            { value: "503", label: "503 (25%)", valor: 25 },
            { value: "504", label: "504 (25%)", valor: 25 },
            { value: "504A", label: "504A (0%)", valor: 0 },
            { value: "504B", label: "504B (35%)", valor: 35 },
            { value: "504C", label: "504C (25%)", valor: 25 },
            { value: "504D", label: "504D (25%)", valor: 25 },
            { value: "504E", label: "504E (22%)", valor: 22 },
            { value: "504F", label: "504F (22%)", valor: 22 },
            { value: "504G", label: "504G (22%)", valor: 22 },
            { value: "504H", label: "504H (22%)", valor: 22 },
            { value: "504I", label: "504I (22%)", valor: 22 },
            { value: "504J", label: "504J (22%)", valor: 22 },
            { value: "505", label: "505 (25%)", valor: 25 },
            { value: "505A", label: "505A (25%)", valor: 25 },
            { value: "505B", label: "505B (25%)", valor: 25 },
            { value: "505C", label: "505C (25%)", valor: 25 },
            { value: "505D", label: "505D (25%)", valor: 25 },
            { value: "505E", label: "505E (25%)", valor: 25 },
            { value: "505F", label: "505F (25%)", valor: 25 },
            { value: "509", label: "509 (25%)", valor: 25 },
            { value: "509A", label: "509A (25%)", valor: 25 },
            { value: "510", label: "510 (25%)", valor: 25 },
            { value: "511", label: "511 (25%)", valor: 25 },
            { value: "512", label: "512 (25%)", valor: 25 },
            { value: "513", label: "513 (25%)", valor: 25 },
            { value: "513A", label: "513A (25%)", valor: 25 },
            { value: "514", label: "514 (25%)", valor: 25 },
            { value: "515", label: "515 (25%)", valor: 25 },
            { value: "516", label: "516 (25%)", valor: 25 },
            { value: "517", label: "517 (25%)", valor: 25 },
            { value: "518", label: "518 (25%)", valor: 25 },
            { value: "519", label: "519 (25%)", valor: 25 },
            { value: "520A", label: "520A (25%)", valor: 25 },
            { value: "520B", label: "520B (25%)", valor: 25 },
            { value: "520D", label: "520D (25%)", valor: 25 },
            { value: "520E", label: "520E (0%)", valor: 0 },
            { value: "520F", label: "520F (25%)", valor: 25 },
            { value: "520G", label: "520G (25%)", valor: 25 },
            { value: "521", label: "521 (1%)", valor: 1 },
            { value: "523A", label: "523A (22%)", valor: 22 },
            { value: "525", label: "525 (0%)", valor: 0 },
        ]
    }
}

export const paises = [
    { value: "301", label: "AFGANISTAN" },
    { value: "594", label: "AGUAS INTERNACIONALES" },
    { value: "201", label: "ALBANIA" },
    { value: "207", label: "ALBORAN Y PEREJIL" },
    { value: "202", label: "ALEMANIA" },
    { value: "595", label: "ALTO VOLTA" },
    { value: "16", label: "AMERICAN SAMOA" },
    { value: "233", label: "ANDORRA" },
    { value: "454", label: "ANGOLA" },
    { value: "109", label: "ANGUILA" },
    { value: "134", label: "ANTIGUA Y BARBUDA" },
    { value: "140", label: "ANTILLAS HOLANDESAS" },
    { value: "302", label: "ARABIA SAUDITA" },
    { value: "403", label: "ARGELIA" },
    { value: "101", label: "ARGENTINA" },
    { value: "356", label: "ARMENIA" },
    { value: "141", label: "ARUBA" },
    { value: "501", label: "AUSTRALIA" },
    { value: "203", label: "AUSTRIA" },
    { value: "347", label: "AZERBAIJAN" },
    { value: "129", label: "BAHAMAS" },
    { value: "327", label: "BAHREIN" },
    { value: "328", label: "BANGLADESH" },
    { value: "130", label: "BARBADOS" },
    { value: "241", label: "BELARUS" },
    { value: "204", label: "BELGICA" },
    { value: "135", label: "BELICE" },
    { value: "429", label: "BENIN" },
    { value: "142", label: "BERMUDA" },
    { value: "596", label: "BIELORRUSIA" },
    { value: "102", label: "BOLIVIA" },
    { value: "242", label: "BOSNIA Y HERZEGOVINA" },
    { value: "430", label: "BOTSWANA" },
    { value: "74", label: "BOUVET ISLAND" },
    { value: "103", label: "BRASIL" },
    { value: "344", label: "BRUNEI DARUSSALAM" },
    { value: "205", label: "BULGARIA" },
    { value: "402", label: "BURKINA FASO" },
    { value: "404", label: "BURUNDI" },
    { value: "329", label: "BUTAN" },
    { value: "456", label: "CABO VERDE" },
    { value: "304", label: "CAMBOYA" },
    { value: "405", label: "CAMERUN" },
    { value: "104", label: "CANADA" },
    { value: "228", label: "CANARIAS ISLAS" },
    { value: "433", label: "CHAD" },
    { value: "108", label: "CHILE" },
    { value: "331", label: "CHINA POPULAR" },
    { value: "332", label: "CHIPRE" },
    { value: "105", label: "COLOMBIA" },
    { value: "458", label: "COMORAS" },
    { value: "406", label: "CONGO" },
    { value: "330", label: "COREA DEL SUR" },
    { value: "306", label: "COREA NORTE" },
    { value: "432", label: "COSTA DE MARFIL" },
    { value: "106", label: "COSTA RICA" },
    { value: "597", label: "COTE DÍVOIRE" },
    { value: "243", label: "CROACIA" },
    { value: "107", label: "CUBA" },
    { value: "127", label: "CURAZAO" },
    { value: "598", label: "CYPRUS" },
    { value: "208", label: "DINAMARCA" },
    { value: "459", label: "DJIBOUTI" },
    { value: "136", label: "DOMINICA" },
    { value: "593", label: "ECUADOR" },
    { value: "434", label: "EGIPTO" },
    { value: "123", label: "EL SALVADOR" },
    { value: "333", label: "EMIRATOS ARABES UNIDOS" },
    { value: "463", label: "ERITREA" },
    { value: "252", label: "ESLOVAQUIA" },
    { value: "244", label: "ESLOVENIA" },
    { value: "209", label: "ESPAÑA" },
    { value: "110", label: "ESTADOS UNIDOS" },
    { value: "245", label: "ESTONIA" },
    { value: "407", label: "ETIOPIA" },
    { value: "600", label: "FALKLAND ISLANDS" },
    { value: "506", label: "FIJI" },
    { value: "308", label: "FILIPINAS" },
    { value: "212", label: "FINLANDIA" },
    { value: "211", label: "FRANCIA" },
    { value: "260", label: "FRENCH SOUTHERN TERRITORIES" },
    { value: "435", label: "GABON" },
    { value: "408", label: "GAMBIA" },
    { value: "999", label: "GENERAL" },
    { value: "246", label: "GEORGIA" },
    { value: "436", label: "GHANA" },
    { value: "239", label: "GIBRALTAR" },
    { value: "131", label: "GRANADA" },
    { value: "214", label: "GRECIA" },
    { value: "247", label: "GROENLANDIA" },
    { value: "143", label: "GUADALUPE" },
    { value: "517", label: "GUAM" },
    { value: "111", label: "GUATEMALA" },
    { value: "831", label: "GUERNSEY" },
    { value: "409", label: "GUINEA" },
    { value: "438", label: "GUINEA ECUATORIAL" },
    { value: "437", label: "GUINEA-BISSAU" },
    { value: "132", label: "GUYANA" },
    { value: "144", label: "GUYANA FRANCESA" },
    { value: "112", label: "HAITI" },
    { value: "113", label: "HONDURAS" },
    { value: "354", label: "HONG KONG" },
    { value: "216", label: "HUNGRIA" },
    { value: "309", label: "INDIA" },
    { value: "310", label: "INDONESIA" },
    { value: "311", label: "IRAK" },
    { value: "312", label: "IRAN (REPUBLICA ISLAMICA)" },
    { value: "217", label: "IRLANDA" },
    { value: "218", label: "ISLANDIA" },
    { value: "145", label: "ISLAS CAIMAN" },
    { value: "518", label: "ISLAS COCOS (KEELING)" },
    { value: "519", label: "ISLAS COOK" },
    { value: "253", label: "ISLAS FAROE" },
    { value: "343", label: "ISLAS HEARD Y MCDONALD" },
    { value: "520", label: "ISLAS NAVIDAD" },
    { value: "146", label: "ISLAS VIRGENES (BRITANICAS)" },
    { value: "833", label: "ISLE OF MAN" },
    { value: "313", label: "ISRAEL" },
    { value: "219", label: "ITALIA" },
    { value: "114", label: "JAMAICA" },
    { value: "314", label: "JAPON" },
    { value: "499", label: "JERSEY" },
    { value: "832", label: "JERSEY" },
    { value: "147", label: "JOHNSTON ISLA" },
    { value: "315", label: "JORDANIA" },
    { value: "348", label: "KAZAJSTAN" },
    { value: "439", label: "KENIA" },
    { value: "349", label: "KIRGUIZISTAN" },
    { value: "510", label: "KIRIBATI" },
    { value: "316", label: "KUWAIT" },
    { value: "317", label: "LAOS, REP. POP. DEMOC." },
    { value: "601", label: "LATVIA" },
    { value: "440", label: "LESOTHO" },
    { value: "248", label: "LETONIA" },
    { value: "318", label: "LIBANO" },
    { value: "410", label: "LIBERIA" },
    { value: "602", label: "LIBIA" },
    { value: "234", label: "LIECHTENSTEIN" },
    { value: "249", label: "LITUANIA" },
    { value: "220", label: "LUXEMBURGO" },
    { value: "355", label: "MACAO" },
    { value: "251", label: "MACEDONIA" },
    { value: "412", label: "MADAGASCAR" },
    { value: "319", label: "MALASIA" },
    { value: "413", label: "MALAWI" },
    { value: "335", label: "MALDIVAS" },
    { value: "414", label: "MALI" },
    { value: "221", label: "MALTA" },
    { value: "115", label: "MALVINAS ISLAS" },
    { value: "415", label: "MARRUECOS" },
    { value: "511", label: "MARSHALL ISLAS" },
    { value: "148", label: "MARTINICA" },
    { value: "441", label: "MAURICIO" },
    { value: "416", label: "MAURITANIA" },
    { value: "443", label: "MAYOTTE" },
    { value: "116", label: "MEXICO" },
    { value: "512", label: "MICRONESIA" },
    { value: "521", label: "MIDWAY ISLAS" },
    { value: "250", label: "MOLDOVA" },
    { value: "235", label: "MONACO" },
    { value: "321", label: "MONGOLIA (MANCHURIA)" },
    { value: "149", label: "MONTSERRAT ISLA" },
    { value: "464", label: "MOROCCO" },
    { value: "442", label: "MOZAMBIQUE" },
    { value: "303", label: "MYANMAR (BURMA)" },
    { value: "460", label: "NAMIBIA" },
    { value: "513", label: "NAURU" },
    { value: "336", label: "NEPAL" },
    { value: "117", label: "NICARAGUA" },
    { value: "444", label: "NIGER" },
    { value: "417", label: "NIGERIA" },
    { value: "522", label: "NIUE ISLA" },
    { value: "523", label: "NORFOLK ISLA" },
    { value: "603", label: "NORTHERN MARIANA ISL" },
    { value: "222", label: "NORUEGA" },
    { value: "524", label: "NUEVA CALEDONIA" },
    { value: "503", label: "NUEVA ZELANDA" },
    { value: "337", label: "OMAN" },
    { value: "215", label: "PAISES BAJOS (HOLANDA)" },
    { value: "322", label: "PAKISTAN" },
    { value: "509", label: "PALAO (BELAU) ISLAS" },
    { value: "353", label: "PALESTINA" },
    { value: "118", label: "PANAMA" },
    { value: "507", label: "PAPUA NUEVA GUINEA" },
    { value: "119", label: "PARAGUAY" },
    { value: "120", label: "PERU" },
    { value: "525", label: "PITCAIRN, ISLA" },
    { value: "526", label: "POLINESIA FRANCESA" },
    { value: "223", label: "POLONIA" },
    { value: "224", label: "PORTUGAL" },
    { value: "121", label: "PUERTO RICO" },
    { value: "334", label: "QATAR" },
    { value: "213", label: "REINO UNIDO" },
    { value: "431", label: "REPUBLICA CENTROAFRICANA" },
    { value: "599", label: "REPUBLICA CHECA" },
    { value: "122", label: "REPUBLICA DOMINICANA" },
    { value: "465", label: "REUNION" },
    { value: "225", label: "RUMANIA" },
    { value: "230", label: "RUSIA" },
    { value: "445", label: "RWANDA" },
    { value: "447", label: "SAHARA OCCIDENTAL" },
    { value: "514", label: "SALOMON ISLAS" },
    { value: "504", label: "SAMOA OCCIDENTAL" },
    { value: "137", label: "SAN CRISTOBAL Y NEVIS" },
    { value: "237", label: "SAN MARINO" },
    { value: "139", label: "SAN VICENTE Y LAS GRANAD." },
    { value: "466", label: "SANTA ELENA" },
    { value: "138", label: "SANTA LUCIA" },
    { value: "449", label: "SANTO TOME Y PRINCIPE" },
    { value: "420", label: "SENEGAL" },
    { value: "446", label: "SEYCHELLES" },
    { value: "423", label: "SIERRA LEONA" },
    { value: "338", label: "SINGAPUR" },
    { value: "323", label: "SIRIA" },
    { value: "448", label: "SOMALIA" },
    { value: "339", label: "SRI LANKA (CEILAN)" },
    { value: "604", label: "ST. PIERRE AND MIQUE" },
    { value: "422", label: "SUDAFRICA (CISKEI)" },
    { value: "421", label: "SUDAN" },
    { value: "226", label: "SUECIA" },
    { value: "227", label: "SUIZA" },
    { value: "133", label: "SURINAM" },
    { value: "450", label: "SWAZILANDIA" },
    { value: "605", label: "SYRIAN ARAB REPUBLIC" },
    { value: "325", label: "TAILANDIA" },
    { value: "307", label: "TAIWAN (CHINA)" },
    { value: "350", label: "TAJIKISTAN" },
    { value: "425", label: "TANZANIA" },
    { value: "606", label: "TERRITORIO ANTARTICO BRITANICO" },
    { value: "607", label: "TERRITORIO BRITANICO OCEANO IN" },
    { value: "529", label: "TIMOR DEL ESTE" },
    { value: "451", label: "TOGO" },
    { value: "530", label: "TOKELAI" },
    { value: "508", label: "TONGA" },
    { value: "124", label: "TRINIDAD Y TOBAGO" },
    { value: "452", label: "TUNEZ" },
    { value: "151", label: "TURCAS Y CAICOS ISLAS" },
    { value: "351", label: "TURKMENISTAN" },
    { value: "346", label: "TURQUIA" },
    { value: "515", label: "TUVALU" },
    { value: "229", label: "UCRANIA" },
    { value: "426", label: "UGANDA" },
    { value: "125", label: "URUGUAY" },
    { value: "352", label: "UZBEKISTAN" },
    { value: "516", label: "VANUATU" },
    { value: "238", label: "VATICANO (SANTA SEDE)" },
    { value: "126", label: "VENEZUELA" },
    { value: "341", label: "VIETNAM" },
    { value: "152", label: "VIRGENES,ISLAS(NORT.AMER.)" },
    { value: "531", label: "WAKE ISLA" },
    { value: "532", label: "WALLIS Y FUTUNA, ISLAS" },
    { value: "342", label: "YEMEN" },
    { value: "231", label: "YUGOSLAVIA" },
    { value: "453", label: "ZAIRE" },
    { value: "427", label: "ZAMBIA" },
    { value: "419", label: "ZIMBABWE (RHODESIA)" },
    { value: "428", label: "ÅLAND ISLANDS" }
]

export const incoTerms = [
    { value: "CIF", label: "CIF" },
    { value: "FOB", label: "FOB" },
    { value: "EXW", label: "EXW" },
    { value: "DAP", label: "DAP" },
    { value: "DAT", label: "DAT" },
    { value: "FAS", label: "FAS" },
    { value: "DDP", label: "DDP" },
    { value: "FCA", label: "FCA" },
]

export const unidadesTiempo = [
    { value: "DIAS", label: "DIAS" },
    { value: "MESES", label: "MESES" },
    { value: "AÑOS", label: "AÑOS" },
]

export const estadosPago = [
    { value: 1, label: "PENDIENTE" },
    { value: 2, label: "PAGADO" },
    { value: 0, label: "NO APLICA" }
]

export const tiposDeCarga = [
    { value: ".xml", label: "INDIVIDUAL (.xml)" },
    { value: ".txt", label: "GRUPAL (.txt)" },
]

export const permisos = {
    ADMIN_PUNTOSVENTA: "ADM_PUN",
    ADMIN_SUCURSALES: "ADM_SUC",
    ADMIN_USUARIOS: "ADM_USU",
    ADMIN_CLIENTES: "ADM_CLI",
    ADMIN_ITEMS: "ADM_ITE",
    EDITAR_EMPRESA: "EDI_EMP",
    CARTERA_PAGOS: "CAR_PAG",
    GENERAR_NUEVO_DOC: "GEN_NUE",
    REENVIAR_CORREO: "REE_COR",
    VER_CLIENTE: "VER_CLI",
    VER_DOCUMENTOS: "VER_DOC",
    VER_EMPRESA: "VER_EMP",
    VER_ERRORES: "VER_ERR",
    VER_ITEMS: "VER_ITE",
    VER_SUCURSALES: "VER_SUC"
}

/* DEFAULT VALUES */
export const cedulaValue = tiposIdentificacion.find(e => e.value === 0)
export const cedulaSRIValue = tiposIdentificacionSRI.find(e => e.value === '05')
export const consumidorFinalValue = tiposIdentificacionSRI.find(e => e.value === '07')
export const produccionValue = ambientesSRI.find(e => e.value === (process.env.NODE_ENV === 'production' ? 2 : 1))
export const efectivoValue = formasPago.find(e => e.value === '01')
export const tipoDeCargaXML = tiposDeCarga.find(e => e.value === '.xml')
export const tipoImpuestoValue = valor => tiposImpuestos.find(e => e.value === valor)
export const tipoIdentificacionSRIValue = valor => tiposIdentificacionSRI.find(e => e.value === valor)
export const tipoIdentificacionValue = valor => tiposIdentificacion.find(e => e.value === valor)